"""Prevent: stop known bugs from being committed again.

  - a git pre-commit hook that checks the lines being committed against company bug knowledge
    and blocks the commit if they repeat a known bug (bypass: git commit --no-verify);
  - an export of the knowledge as Semgrep rules, so IDEs and other CI tools flag the patterns too.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

import debug

MARKER = "# bug-vaccine-guard"


def hooks_dir(repo):
    out = subprocess.run(["git", "rev-parse", "--git-path", "hooks"], cwd=repo, capture_output=True, text=True)
    if out.returncode:
        raise ValueError(f"{repo} is not a git repository")
    return (Path(repo) / out.stdout.strip()).resolve()


def hook_script(tool, python=sys.executable, kb=None):
    py = Path(python).as_posix()
    kb_arg = f' --kb "{Path(kb).resolve().as_posix()}"' if kb else ""
    return f"""#!/bin/sh
{MARKER}: blocks commits that repeat a bug this company has already fixed.
# Installed by `bugvaccine.py guard install`. Remove with `bugvaccine.py guard uninstall`.
# Emergency bypass (please don't make it a habit): git commit --no-verify
"{py}" "{Path(tool).as_posix()}" guard check .{kb_arg}
"""


def install(repo, tool, kb=None):
    d = hooks_dir(repo)
    d.mkdir(parents=True, exist_ok=True)
    hook = d / "pre-commit"
    if hook.exists() and MARKER not in hook.read_text(encoding="utf-8", errors="replace"):
        raise ValueError(f"{hook} already exists and isn't ours. Add this line to it instead:\n"
                         f"  python \"{Path(tool).as_posix()}\" guard check .")
    hook.write_bytes(hook_script(tool, kb=kb).encode("utf-8"))
    try:
        hook.chmod(0o755)
    except OSError:
        pass
    return hook


def uninstall(repo):
    hook = hooks_dir(repo) / "pre-commit"
    if hook.exists() and MARKER in hook.read_text(encoding="utf-8", errors="replace"):
        hook.unlink()
        return True
    return False


def staged_diff(repo):
    return subprocess.run(["git", "diff", "--cached", "--unified=0", "--no-color"], cwd=repo, capture_output=True,
                          text=True, encoding="utf-8", errors="replace").stdout


def check(repo, kb):
    """Findings for the staged changes (only the lines being added)."""
    return debug.match_diff(staged_diff(repo), kb)


# ── Semgrep export ─────────────────────────────────────────────────────────

SEMGREP_LANG = {"javascript": ["javascript", "typescript"], "python": ["python"], "java": ["java"], "go": ["go"]}


def _q(s):
    return json.dumps(str(s), ensure_ascii=False)   # a JSON string is a valid YAML double-quoted scalar


def semgrep_rules(kb):
    lines = ["# Generated by bugvaccine.py rules: bugs this company has already fixed.",
             "# Each rule flags code that matches a known bug's signature. Regenerate after `learn`.", "rules:"]
    count = 0
    for a in kb["antigens"]:
        s = a.get("signatures", {})
        for i, c in enumerate(s.get("code", []), 1):
            count += 1
            rid = re.sub(r"[^a-z0-9-]+", "-", f"bug-vaccine-{a['key']}-{i}".lower()).strip("-")
            msg = f"{a.get('title', a['key'])}: {c.get('explain', '')}"
            if s.get("fix_hint"):
                msg += f" How it was fixed before: {s['fix_hint']}"
            lines += [f"  - id: {rid}",
                      f"    message: {_q(msg)}",
                      f"    severity: WARNING",
                      f"    languages: {json.dumps(SEMGREP_LANG.get(s.get('lang'), ['generic']))}",
                      f"    pattern-regex: {_q(c['regex'])}",
                      f"    metadata:",
                      f"      source: {_q(a.get('source_commit', ''))}",
                      f"      postmortem: {_q(a.get('postmortem', ''))}",
                      f"      project: {_q(a.get('repo', ''))}"]
    return "\n".join(lines) + "\n", count
